update : translation changes
romain-gilliotte/byte-of-python pull request #1
Opened 2020-05-27 15:55 UTC by mattiasduerrmeier

Propositions d'améliorations de la traduction française de "Byte of Python".

2020-08-08 20:30 UTC, romain-gilliotte requested changes
Bonjour

Merci beaucoup pour les corrections!
Je ne m'attendais pas à des contributions, mais elles sont bienvenues, et c'est vrai que le style laisse à désirer! 

J'avais repris et mise à jour une ancienne traduction du livre (en format mediawiki) et je l'avais republiée car j'avais besoin d'un support de cours en français.

Désolé d'avoir mis aussi longtemps à faire la review. Si vous voulez faire les qques corrections en commentaire, je vous accepte la PR.

(sinon n'hesitez pas à me dire, j'accepte et je fais les corrections dans un autre commit)

2020-08-08 20:30 UTC, romain-gilliotte commented on about_python.md
> +> Python est un langage de programmation facile à apprendre et puissant. Il possède des structures de données de haut niveau et une approche simple mais efficace à la programmation orientée objet. La
La typographie est liée à l'utilisation de polices de caractères. On parle ici de types (entier, chaine de caractères, ...)

2020-08-08 20:30 UTC, romain-gilliotte commented on README.md
> +Ce livre vous apprendra à utiliser Python version 3. Il vous aidera également a utiliser la version 2 de Python, plus ancienne et plus courante.
Manque accent

2020-08-08 20:30 UTC, romain-gilliotte commented on preface.md
> +Python est sans doute l'un des rares langages de programmation à la fois simple et puissant. C'est une bonne chose pour les débutants comme pour les experts; plus important encore, c'est un language
"c'est un language de programmation amusant de s'en servir" sonne mal

2020-09-24 20:53 UTC, mattiasduerrmeier commented
Bonsoir,
Désolé pour la réponse tardive.
Je viens de terminer les corrections. Vous pouvez accepter la PR.

Je pense probablement recommencer à relire et corriger ce livre durant les prochaines semaines.

2020-09-24 22:09 UTC, merged

2020-09-24 22:15 UTC, romain-gilliotte commented
C'est mergé!

Merci pour cette première contribution!
La version publiée sur gitbook s'est mise à jour avec les modifications